---

- name: Test if X-Pack is installed
  shell: "/usr/share/kibana/bin/kibana-plugin list | grep x-pack"
  become: yes
  register: x_pack_installed
  changed_when: False
  failed_when: "'ERROR' in x_pack_installed.stdout"
  check_mode: no
  ignore_errors: yes

- name: Remove X-Pack plugin
  command: "/usr/share/kibana/bin/kibana-plugin remove x-pack"
  become: yes
  register: xpack_state
  failed_when: "'ERROR' in xpack_state.stdout"
  changed_when: xpack_state.rc == 0
  when: x_pack_installed.rc == 0 and (not kibana_install_xpack)
  notify: restart kibana

- name: Install X-Pack plugin
  command: >
    /usr/share/kibana/bin/kibana-plugin install --silent x-pack
  become: yes
  register: xpack_state
  failed_when: "'ERROR' in xpack_state.stdout"
  changed_when: xpack_state.rc == 0
  when: x_pack_installed.rc == 1 and kibana_install_xpack
  notify: restart kibana